#ifndef INDEX_HTML_H
#define INDEX_HTML_H

const char INDEX_HTML[] PROGMEM = 
"<!DOCTYPE html><html lang=en><meta charset=UTF-8><meta name=viewport content=\"w"
"idth=device-width,initial-scale=1\"><title>Atomic Vmix ATEM Tally Configurator</"
"title><script src=https://code.jquery.com/jquery-3.6.0.min.js></script><script s"
"rc=https://cdn.tailwindcss.com></script><script src=https://cdn.jsdelivr.net/npm"
"/feather-icons/dist/feather.min.js></script><body class=\"bg-gray-100 p-8\"><div"
" class=\"max-w-6xl mx-auto bg-white p-6 rounded-lg shadow-md\"><h1 class=\"text-"
"2xl font-bold mb-6\">Atomic Vmix ATEM Tally Configurator</h1><div class=mb-6><la"
"bel for=deviceIp class=\"block mb-2 font-semibold\">Device IP:</label><div class"
"=flex><input id=deviceIp class=\"flex-grow p-2 border rounded-l\" placeholder=\""
"e.g., 10.9.11.236\"><button id=loadConfig class=\"bg-blue-500 text-white px-4 py"
"-2 rounded-r hover:bg-blue-600\">Load</button></div></div><div id=configSection "
"class=hidden><div class=mb-6><label for=vmixIp class=\"block mb-2 font-semibold\""
">vMix IP:</label><div class=flex><input id=vmixIp class=\"flex-grow p-2 border r"
"ounded-l\" placeholder=\"e.g., 192.168.10.140\"><button id=saveVmixIp class=\"bg"
"-green-400px-4 py-2 rounded-r hover:bg-green-600\">Save</button></div></div><div"
" id=cameraBoxes class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"></div></div></di"
"v><script>$(document).ready(function(){function a(){let l=$(\"#deviceIp\").val()"
";l?$.getJSON(\"http://\"+l).done(function(a){$(\"#vmixIp\").val(a.vmixip||\"\"),"
"$(\"#cameraBoxes\").empty();for(let e=0;e<10;e++){var t=a[\"input\"+e]||1,n=a[\""
"cam\"+e]||1;$(\"#cameraBoxes\").append(`<div class=\"p-4 border rounded\"><h2 cl"
"ass=\"text-lg font-semibold mb-2\">Camera ${(i=e)+1}</h2><div class=\"flex items"
"-center space-x-2\"><div class=\"flex-1 p-2 border rounded\"><label class=block>"
"<span class=\"block mb-1\">vMix Input:</span><div class=flex><button class=\"dec"
"rement bg-gray-200 px-2 rounded-l\" data-target=vmixInput${i}>-</button><input t"
"ype=number id=vmixInput${i} class=\"w-full p-1 border text-center bg-gray-100\" "
"value=${t} min=1><button class=\"increment bg-gray-200 px-2 rounded-r\" data-tar"
"get=vmixInput${i}>+</button></div></label></div><i data-feather=arrow-right></i>"
"<div class=\"flex-1 p-2 border rounded\"><label class=block><span class=\"block "
"mb-1\">ATEM Camera ID:</span><div class=flex><button class=\"decrement bg-gray-2"
"00 px-2 rounded-l\" data-target=atemCam${i}>-</button><input type=number id=atem"
"Cam${i} class=\"w-full p-1 border text-center bg-gray-100\" value=${n} min=1><bu"
"tton class=\"increment bg-gray-200 px-2 rounded-r\" data-target=atemCam${i}>+</b"
"utton></div></label></div></div><button class=\"saveCameraSettings mt-2 bg-green"
"-400 px-4 py-2 rounded hover:bg-opacity-80 w-full\" data-index=${i}>Save</button"
"></div>`)}$(\"#configSection\").removeClass(\"hidden\"),feather.replace();var i,"
"e=l;e=window.location.protocol+\"//\"+window.location.host+window.location.pathn"
"ame+\"?ip=\"+e,window.history.pushState({path:e},\"\",e)}).fail(function(){alert"
"(\"Failed to load configuration\")}):alert(\"Please enter Device IP\")}var e=new"
" URLSearchParams(window.location.search).get(\"ip\");e&&($(\"#deviceIp\").val(e)"
",a()),$(\"#loadConfig\").click(a),$(\"#deviceIp\").keypress(function(e){if(13==e"
".which)return a(),!1}),$(document).on(\"click\",\".increment, .decrement\",funct"
"ion(){var e=$(\"#\"+$(this).data(\"target\")),a=parseInt(e.val())||0;e.val(a+($("
"this).hasClass(\"increment\")?1:-1))}),$(\"#saveVmixIp\").click(function(){var e"
"=$(\"#deviceIp\").val(),a=$(\"#vmixIp\").val();e&&a?$.get(`http://${e}/save?vmix"
"ip=`+a).done(function(){alert(\"vMix IP saved successfully\")}).fail(function(){"
"alert(\"Failed to save vMix IP\")}):alert(\"Please enter both Device IP and vMix"
" IP\")}),$(document).on(\"click\",\".saveCameraSettings\",function(){let e=$(thi"
"s).data(\"index\");var a=$(\"#deviceIp\").val(),t=$(\"#vmixInput\"+e).val(),n=$("
"\"#atemCam\"+e).val();a?$.get(`http://${a}/save?input${e}=${t}&cam${e}=`+n).done"
"(function(){alert(`Camera ${e+1} settings saved successfully`)}).fail(function()"
"{alert(`Failed to save Camera ${e+1} settings`)}):alert(\"Please enter Device IP"
"\")})})</script>";

#endif // INDEX_HTML_H